compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: "./src/unifolm_vla/config/deepseeds/ds_config.yaml"
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
num_machines: 1
num_processes: 8